language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6.1"
# command to install dependencies
install:
  - pip install request lxml pandas numpy matplotlib tushare
# command to run tests
script: pytest
